package protocol

import (
	"client/utils"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"io"
	"math"
	"os"
	"strings"
	"syscall"

	"github.com/pkg/xattr"
	"golang.org/x/sys/unix"
)

type FileMetaData struct {
	Name      string
	Hash      string
	BufSize   uint64
	BlockSize int64
	Pieces    uint64
}

const FILE_HASH_SIZE = 64
const PIECE_SIZE = (256 * 1024)
const PIECE_HEADER_SIZE = 8 + 64
const ATTRIBUTE_STRING = "user.file_hash"

// used for RPC Message by requester
type FileRequest struct {
	Hash     string
	Interest int64
}

// used for RPC Message by receiver to reply to the iniator
// BUG: size only 24, where actual data is 72 bytes
type PieceHeader struct {
	FileHash  FileHash
	PieceSize uint64 // from blockSize or remaining bytes
}

// Hash(64 long characters) & PieceSize 8 bytes
func ParsePieceHeader(buf *[]byte) (Header PieceHeader, Error error) {
	header := (*buf)[:PIECE_HEADER_SIZE]
	ps := binary.LittleEndian.Uint64(header[FILE_HASH_SIZE : FILE_HASH_SIZE+PIECE_HEADER_SIZE])

	ph := PieceHeader{
		FileHash:  string(header[:FILE_HASH_SIZE]),
		PieceSize: ps,
	}

	return ph, nil
}

// ClusterName is var length (runtime)
// Hash is FILE_HASH_SIZE 64 bytes
// Size is 8 bytes
// Payload is fixed 256KB
// Piece Header -> [Hash, PayloadSize] -> [PayLoad]
// path + file_name
func CreateDataPiece(path string, fr FileRequest) (DataPiece *[]byte, Error error) {

	fmt.Printf("[ PIECE CREATION ]: Creating Pieces for %s\n", fr.Hash)
	fileBuf, err := ReadFileBuf(path, fr)
	if err != nil {
		return nil, err
	}

	DataPieceBuffer := make([]byte, 0, PIECE_HEADER_SIZE+PIECE_SIZE)

	pieceSizeBuf := make([]byte, 8)

	n := binary.PutUvarint(pieceSizeBuf, PIECE_SIZE)

	if n < 1 {
		return nil, fmt.Errorf("unable to write piece size to buffer")
	}

	fmt.Printf("String Hash: %s, Buf: %s\n", fr.Hash, []byte(fr.Hash))
	fmt.Printf("Payload Size: %d\n", pieceSizeBuf)

	DataPieceBuffer = append(DataPieceBuffer, []byte(fr.Hash)...)
	fmt.Printf("Hash: %s\n", DataPieceBuffer[:FILE_HASH_SIZE])

	DataPieceBuffer = append(DataPieceBuffer, pieceSizeBuf[:n]...)
	fmt.Printf("pieceSizeBuf: %d\n", DataPieceBuffer[FILE_HASH_SIZE:PIECE_HEADER_SIZE])

	DataPieceBuffer = append(DataPieceBuffer, fileBuf...)

	return &DataPieceBuffer, nil
}

func ReadFileBuf(path string, fr FileRequest) ([]byte, error) {

	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}

	buf, err := syscall.Mmap(int(f.Fd()), fr.Interest*PIECE_SIZE, PIECE_SIZE, syscall.PROT_READ, syscall.MAP_SHARED)

	if err != nil {
		fmt.Println("[ PIECE CREATION ]: Error accessing memory mapped disk")
		return nil, err
	}
	fileInfo, err := f.Stat()
	if err != nil {
		return []byte{}, err
	}
	// if the remaining bytes is less than the block size, then only read the remaining bytes
	rem := min(PIECE_SIZE, fileInfo.Size()-(fr.Interest*PIECE_SIZE))
	tmp := make([]byte, rem)
	copy(tmp, buf[:rem])

	err = syscall.Munmap(buf)
	if err != nil {
		fmt.Println("[ PIECE CREATION ]: Error accessing memory mapped disk")
		return nil, err
	}
	return tmp, nil
}

// The server generates unique `HashID` when user's uploads a file.
// So if a client requests to upload a file, the client would receive a `HashID`
// generated by the server which then the client uses `extended file attributes`
// to make it so we can extend the prefix header of the current file and store
// the `HashID` within that header.
func NewFileMetaData(fileSource string) (FileMetaData, error) {

	fmt.Printf("[ METAFILE ]: Checking if the file '%s' Exists\n", fileSource)
	file, err := os.Open(fileSource)
	if err != nil {
		fmt.Println("[ METAFILE ]: Unable to Open File")
		return FileMetaData{}, err
	}

	defer file.Close()

	fmt.Printf("[ METAFILE ]: The file '%s' Exists\n", fileSource)
	fmt.Printf("[ EMBEDDING ]: Embedding HashID to '%s'\n", fileSource)
	hash, err := GenerateFileHashID(file)
	if err != nil {
		return FileMetaData{}, nil
	}
	err = EmbbedFileHashID(hash, file)
	if err != nil {
		fmt.Printf("[ EMBEDDING ]: Failed to Embed hash in '%s'\n", fileSource)
		return FileMetaData{}, nil
	}
	fmt.Printf("[ EMBEDDING ]: Successfully Embedded HashID in '%s'\n", fileSource)

	fileInfo, err := file.Stat()
	if err != nil {
		return FileMetaData{}, nil
	}

	fileSize := uint64(fileInfo.Size())

	newMetaData := FileMetaData{
		Name:      file.Name(),
		Hash:      hash,
		BufSize:   fileSize,
		BlockSize: PIECE_SIZE,
	}
	newMetaData.Pieces = uint64(math.Ceil(float64(newMetaData.BufSize) / float64(newMetaData.BlockSize)))

	return newMetaData, nil
}
func GenerateFileHashID(file *os.File) (FileHash, error) {
	hash := sha256.New()
	_, err := io.Copy(hash, file)
	if err != nil {
		return "", err
	}

	return hex.EncodeToString(hash.Sum(nil)), nil
}

// `src` refers to the file eg: `/<path>/<to>/<file>/src_file.sh`
// attribute string: "user.file_hash"
func EmbbedFileHashID(hash FileHash, file *os.File) error {
	err := unix.Fsetxattr(int(file.Fd()), ATTRIBUTE_STRING, []byte(hash), 0)
	if err != nil {
		fmt.Println("[ EMBEDDING ]: Unable to set an extended attribute to file")
		return err
	}
	return nil
}

// Always should be ran before creating data pieces to verify its existence
func Checkfile(fileHash FileHash, FILE_LOCATION string) (Entry os.DirEntry, Path string, Error error) {

	programwd, err := os.Getwd()
	if err != nil {
		fmt.Printf("Error Unable to Read Get Current Working Directory\n")
		fmt.Printf("Reason: %s\n", err)
		return nil, "", err
	}
	wd := []string{programwd}
	wd = append(wd, FILE_LOCATION)

	fmt.Println(wd)
	entries, err := os.ReadDir(utils.ConcatStr(&wd))

	entry, err := recursiveFileSearch(fileHash, entries, &wd)

	if err != nil {
		return nil, "", fmt.Errorf("No entries matching the fileKey.")
	}

	return entry, utils.ConcatStr(&wd), nil
}

func VerifyEmbeddedHash(src string, hashID FileHash, key string) (bool, string, error) {

	b, err := xattr.Get(src, key)
	if err != nil {
		return false, "", err
	}
	if strings.Compare(string(b), hashID) != 0 {
		return false, "", nil
	}
	return true, string(b), nil

}

// initializes `wd` with the current working directory of the program
// appended with the file location of the user and as `entries` array is iterated
// and if the current entry is a Directory the `wd` is appended with the current name
// of the directory, and if not then continue.
// If the current file is not a directory and matches the `fileKey` the return the entry of that file
func recursiveFileSearch(fileHash FileHash, entries []os.DirEntry, wd *[]string) (os.DirEntry, error) {
	for _, entry := range entries {
		info, err := entry.Info()
		entryName := info.Name()
		fmt.Printf("[ File Search ]: Entry located: %s\n", entryName)
		if err != nil {
			fmt.Printf("Error Unable to get info for file: %s\n", entryName)
			fmt.Printf("Reason: %s\n", err)
			continue
		}
		if !info.IsDir() {
			srcPath := utils.ConcatStr(wd) + entryName
			fmt.Printf("[ File Search ]: Info.Name: `%s` - Current WD: '%s'\n", info.Name(), srcPath)
			hashBuf, err := xattr.Get(srcPath, ATTRIBUTE_STRING)
			if err != nil {
				fmt.Println("[ File Search ]: Unable to get extended attribute")
				return nil, err
			}
			bufToStr := string(hashBuf)
			if strings.Compare(bufToStr, fileHash) != 0 {
				fmt.Printf("[ File Search ]: '%s' Not Matching hash to '%s'\n", entryName, fileHash)
				continue
			}
			fmt.Printf("[ File Search ]: Found matching hash values: '%s' on '%s'\n", info.Name(), bufToStr)
			return entry, nil
		}
		fmt.Println("[ File Search ]: Skipping directory")
		currentDirectory := entryName + "/"
		*wd = append(*wd, currentDirectory)
		curDirEntries, err := os.ReadDir(utils.ConcatStr(wd))
		if err != nil {
			*wd = (*wd)[:len(*wd)-1]
			fmt.Printf("Error Unable to Read from Directory: %s\n", entryName)
			fmt.Printf("Reason: %s\n", err)
			continue
		}
		// back tracks the stack to continue to the next file if the current directory
		// exhausted all the entries it has and moves on to the adjacent entry
		foundEntry, err := recursiveFileSearch(fileHash, curDirEntries, wd)
		if err != nil {
			*wd = (*wd)[:len(*wd)-1]
			continue
		}

		fmt.Printf("[ File Search ]: Found File: %s\n", entryName)
		return foundEntry, nil
	}
	return nil, fmt.Errorf("No entries matching the fileKey.")
}
